spring:
  application:
    name:
      game-catalog-with-spring-boot
  datasource:
      url: jdbc:h2:mem:game-catalog
      username: sa
      password: password
      driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
  logging: Debug