spring:
  application:
    name:
      game-catalog-with-spring-boot
  datasource:
      url: jdbc:postgresql://localhost:5432/game_catalog
      username: admin
      password: admin
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  logging: Debug